title: "Anuva Negi"
name: "Anuva Negi"
description: "MS Data Science student | Machine Learning & Analytics"
url: "https://silverfrost702.github.io"

github_username: silverfrost702
twitter_username:

minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Output settings
permalink: /:categories/:title/
paginate: 0
paginate_path: /page:num/
timezone:

include:
  - _pages

collections:
  posts:
    output: false

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name: "Anuva Negi"
  # avatar: "/assets/images/bio-photo.jpg"
  bio: "I'm a Data Science graduate student at the University of Texas at Arlington, passionate about applying data-driven methods to solve real-world problems. My work integrates data visualization, statistical modeling, predictive analytics, and machine learning to deliver actionable insights from complex datasets."
  location: "Dallas, TX"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/silverfrost702"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/anuva-negi"
